name 'wsus'
maintainer 'Laura Melton'
maintainer_email 'melton@tamu.edu'
license 'All Rights Reserved'
description 'Installs/Configures wsus'
long_description 'Installs/Configures wsus'
version '0.1.0'
chef_version '>= 13.0'
supports 'windows'

issues_url 'https://github.com/tamucookbooks/wsus/issues'
source_url 'https://github.com/tamucookbooks/wsus.git'
